// writes .env.development.local from the running local supabase, so
// `next dev` talks to it instead of the real project (.env.local stays as is).
// runs at the end of `npm run db:start`; safe to rerun any time.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const status = JSON.parse(
  execSync("npx -y supabase@2 status -o json", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }),
);

const env = {
  SUPABASE_URL: status.API_URL,
  SUPABASE_PUBLISHABLE_KEY: status.PUBLISHABLE_KEY,
  SUPABASE_SECRET_KEY: status.SECRET_KEY,
  SITE_URL: "http://localhost:3000",
};

writeFileSync(
  ".env.development.local",
  "# generated by `npm run db:start` (scripts/db-env.mjs): local supabase.\n" +
    "# overrides .env.local during `next dev` only. delete it to go back to the real project.\n" +
    Object.entries(env).map(([k, v]) => `${k}=${v}`).join("\n") +
    "\n",
);
console.log("wrote .env.development.local (local supabase)");
